import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import octokit from "../utils/octokit";
import { Dropdown } from "../components/dropdown";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, setUser] = useState(Array);
  const [search, setSearch] = useState("");

  const getUser = async (e: any) => {
    e.preventDefault();
    const result = await octokit.request("GET /search/users", {
      q: search,
    });
    console.log(result);
    setUser(result.data.items.slice(0, 5));
    console.log(user);
  };

  const onChange = (e: any) => {
    setSearch(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Github Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form
          className="flex items-center flex-col"
          onSubmit={(e) => getUser(e)}
        >
          <input
            type="text"
            className="w-60 h-8 p-2 bg-gray-200 text-gray-700 font-normal rounded-sm mt-10"
            value={search}
            onChange={(e) => onChange(e)}
          />
          <button
            className="bg-blue-700 w-60 h-10 rounded-md font-medium hover:bg-blue-600 hover:text-white active:bg-blue-700 mt-5"
            type="submit"
          >
            Search
          </button>
        </form>
        {!user.length ? (
          <></>
        ) : (
          <p className="flex items-center mt-2 font-normal flex-col">
            Showing users for {search}
          </p>
        )}
        <section className="flex flex-col items-center mt-2">
          {!user.length ? (
            <></>
          ) : (
            user.map((item: any) => (
              <Dropdown key={item.id} login={item.login} />
            ))
          )}
        </section>
      </main>
    </>
  );
}
